### ISSUE TITLE
Add stub methods for when raven not initialised

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-errors#10]
As discussed on slack:

Rhys Evans [9:46 AM] 
@samuel.giles: I'm looking into using o-errors in next. One feature our current implementation has is that raven can be turned off using a feature flag, but the methods are all mocked in that case and can still be called without erroring. I could wrap o-errors to preserve this functionality, but is there value in having similar functionality built into o-errors

Sam Giles [11:33 AM] 
wheresrhys: I think adding it into o-errors makes sense.  At the moment you can't really turn off error tracking, you either have tracking or you don't (the best you can do at the moment is 'not' call `init`).  You opt in to logging.

**Comment by kavanagh** [comment]
I'd like this too please.
