### ISSUE TITLE
Config setting for logging errors to the browser's console

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/o-errors#110]
## What
Implement a configuration setting (or extend the `logLevel` setting) that, when switched on/off, logs errors to the console instead of sending them to Sentry.

## Details
The US Growth team recently implemented `o-errors` into an application. During development and testing, we wanted to see the errors logged to the browser's console rather than sending errors to Sentry. We thought setting the `logLevel` to `consoleonly` would achieve this. While this setting does prevent errors being sent to Sentry, the errors aren't logged to the console (the setting [replaces the `raven` methods with no-ops](https://github.com/Financial-Times/o-errors/blob/c8c99899c36221ffa68909204dda4d1fdf0ea1fe/src/js/oErrors.js#L143-L148)).

Other values for the `logLevel` setting only affect `o-errors` [logging methods](https://github.com/Financial-Times/o-errors#log-data-and-associating-logs-with-errors), which makes the `logLevel` setting a little inconsistent and confusing to use.

I suggest either:

* amending the `consoleonly` `logLevel` setting so that it also logs errors to the console, or;
* adding an additional setting mode which prevents errors being sent to Sentry and logs them to the browser's console.

## Additional information
I've spoken to @JakeChampion  about this already: https://financialtimes.slack.com/archives/C02FU5ARJ/p1610984259006200.

I'm also happy to submit a PR to implement this feature but I would appreciate some guidance on which of the two options above you think would be better.

**Comment by JakeChampion** [comment]
Thank you for opening this issue @jamesnicholls 

> I suggest either:
> 
>     * amending the `consoleonly` `logLevel` setting so that it also logs errors to the console, or;

This is the option I would go with 👍 

I'm happy to review any pull-requests for this feature :-)

**Comment by JakeChampion** [comment]
this was done in https://github.com/Financial-Times/o-errors/pull/118
