### ISSUE TITLE
Add offline error tracking support

### ISSUE THREAD

**Issue by samgiles** [Financial-Times/o-errors#18]
FYI: Raven.JS now has a primitive available for this to be implemented here: https://github.com/getsentry/raven-js/pull/335#issuecomment-140559175

cc @pornel useful?

**Comment by pornel** [comment]
Useful, and necessary for the webapp.

**Comment by pornel** [comment]
We're planning to queue requests using this:

http://git.svc.ft.com:8080/projects/FTA/repos/ft-app/browse/lib/javascript/tracking/store.js

**Comment by rowanmanning** [comment]
I spoke to @rowanbeentje about this, and offline errors are really low down the app team's priority list at the moment. Considering the lack of activity on this, I'm going to close. We can reopen if/when the app team have a more pressing need for this
