### ISSUE TITLE
window.onerror handler not installed

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-errors#22]
The documentation says:

> Uncaught errors are handled by a `window.onerror` function installed on initialisation.

However, that doesn't seem to be the case, and I don't see any code that would do it the o-errors source. 
Raven documentation only shows a try/catch examples.

**Comment by tom-parker** [comment]
I think this is handled by Tracekit within Raven. https://github.com/getsentry/raven-js/blob/master/vendor/TraceKit/tracekit.js

I'll add a note to the documentation though as this tripped me up when I was looking at the source

**Comment by AlbertoElias** [comment]
But is it working properly? @pornel seemed to say that it wasn't

**Comment by pornel** [comment]
The webapp calls `oErrors.init({sentryEndpoint: …, enabled: …, siteVersion: …, transformError: …, filterError: …, logLevel: …, tags: …})`, but window.onerror remains `null`.

`oErrors.report()` logs to console that an error is being sent to Sentry, but if I trigger an error outside try/catch (e.g. in an onclick handler) then nothing is reported.

**Comment by tom-parker** [comment]
@pornel can you point me in the direction of where you're initialising o-errors or copy in the options you're passing. We can get the `window.onerror` handler installed fine on next.

**Comment by pornel** [comment]
It's here: http://git.svc.ft.com/projects/FTA/repos/ft-app/browse/lib/javascript/error-reporter/clienterrorreporter.js#12

**Comment by tom-parker** [comment]
This is very strange. I've stepped through the initialisation of `o-errors` locally and after this, the `window.onerror` handler has been successfully installed as seen below 

<img width="1280" alt="screen shot 2015-11-04 at 17 09 57" src="https://cloud.githubusercontent.com/assets/900140/10946038/0a632856-8318-11e5-82c4-baa7cad3e1fc.png">

It seems that something is getting loaded after this that is then clobbering the `onerror` handler?

cc @AlbertoElias

**Comment by pornel** [comment]
Oh! Thanks for the pointer. I've found code in the webapp that was trying to install our old error handler.
