### ISSUE TITLE
Context modified in transformError is not used

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-errors#24]
o-errors can be initialized with a `transformError`  callback. Only `obj.error` result of this callback is used. `obj.context` is ignored.

This makes it impossible to sanitise the context object (e.g to work around #23), and makes it impossible to preserve additional data extracted from the error object.

Both transformed .error and .context results from the transform function should be used instead of original values.

**Comment by tom-parker** [comment]
@pornel I might be missing something but doesn't the whole transformed error replace the original here https://github.com/Financial-Times/o-errors/blob/b6311e80f25957ea57e1f38f107781865d8d81fe/src/js/oErrors.js#L227

**Comment by pornel** [comment]
That's buggy, because it doesn't affect the context here:

https://github.com/Financial-Times/o-errors/blob/b6311e80f25957ea57e1f38f107781865d8d81fe/src/js/oErrors.js#L242

**Comment by pornel** [comment]
The error replacement is not quite correct either, because if the filter function does:

     obj.error = new Error();

then it won't be used, because o-errors will use the error variable directly, which still references the previous object.
