### ISSUE TITLE
How to log all errors to console.error in production

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-errors#32]
Is it safe to use `logLevel: "debug"` in production?

We'd like _all_ errors caught by o-errors to be logged to the error console, so that we can see errors happening when we investigate live issues or when our testers test the app built for deployment.

**Comment by AlbertoElias** [comment]
We don't recommend it, but it's up to you. It also depends what kind of errors you're emitting and if they're safe for everyone to see
