### ISSUE TITLE
Allow window.onerror handler to use o-errors filterError and transformError functions

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/o-errors#43]
o-errors supports options for filterError and transformError callbacks for data transformation, decoration, and rejection.  These get used in `Errors.prototype.report`.

The global window.onerror stack doesn't seem to use these callbacks.  Technically this is probably because the global window error handler gets installed by Sentry, via the TraceKit "vendor" within the Sentry source.  Hopefully it's possible to hook into this and apply the same callbacks we're already applying at the o-errors level; otherwise, we may have to disable the default onerror listener and add our own.

This is important because with a global error handler, third-party errors from adverts, third-party libraries, or injected scripts will all be caught and reported; if any of these are high frequency, they can cause rate limiting or data loss on the error submission endpoint.

Being tracked for the web app at https://jira.ft.com/browse/AT-647 (for internal users!).

**Comment by wheresrhys** [comment]
I think I just fixed this in https://github.com/Financial-Times/o-errors/pull/49

**Comment by rowanbeentje** [comment]
Nice simple fix too, phew :D  Looks the same to me - let's consider this fixed, thank you!
