### ISSUE TITLE
o-catch interface

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-errors#6]
## wrap

`cb = oCatch.wrap(cb)` wraps callback in `try`/`catch` that automatically reports all errors, e.g.

    setTimeout(oCatch.wrap(function(){
        // can fail here
    }), 100);

I'm wondering whether it should support passing context (any object that is used as extra information for any error that is thrown), e.g.

    overlay.open();
    setTimeout(oCatch.wrap({overlay: overlay, delay:delay}, function(){
        overlay.close();
    }), delay);

I'm using `oCatch.wrap(context, cb)`, because `(cb, context)` would be error-prone: the last line in the example above could be either `}), delay);` or  `}, delay));`

## log

https://redmine.labs.ft.com/issues/39982

`oCatch.log(…)`, `oCatch.warn(…)` equivalent of `console.log/warn`, but it would also keep few last messages and add them to the context of any errors reported later, so the person reviewing the report can have an idea what the app was doing.

    oCatch.log("fooing bars");
    foo(bar); // e.g. if foo is undefined, the error will contain "fooing bars" somewhere

## error

`oCatch.error(Error object or message, any context…)` dispatches the error to oErrors, returns Error object. 

It's like o-errors integrated `console.error`, plus returning Error for convenience allows 1-liner catch and rethrows: 

```
…
}
catch(err) {
    throw oCatch.error(err, "failed doing foo", foo, bar);
}
```

and integrates with Promises: `promise.then(…).catch(oCatch.error)` will report promise failure.

WDYT?

**Comment by samgiles** [comment]
The new `oErrors` API supports:

`var wrappedFunc = oErrors.wrap(func);`
`var wrappedFunc = oErrors.wrapWithContext(context, func);`

It's awkward to get these to behave like `console.*` without some serious logic, there is a module that you can use to format - `require('util').format` - but it adds 8K to the minified bundle...

`oErrors.log("A message");`
`oErrors.warn("A warning");`

I may merge these two.

`oErrors.error("An error");`
`throw oErrors.report(e, { optional: "context" });`

**Comment by pornel** [comment]
Re: util.format – [js-abbreviate](http://git.svc.ft.com/projects/LOG/repos/js-abbreviate/browse/index.js) is smaller.
