### ISSUE TITLE
Consider this component for deprecation

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-errors#68]
I think this needs a review of where this is used and how we can phase it out. We probably need to speak to a lot of our users for this. This work should maybe happen before the breaking cascade #66

**Comment by JakeChampion** [comment]
I don't think we can deprecate this component, it is actively used it multiple projects and is used in brand new projects such as Spark.

https://github.com/Financial-Times/spark/blob/960ac39e6fd95d6ef3d7cbe9027ab5a51695517a/package.json#L110
https://github.com/Financial-Times/spark-lists/blob/a21e8def9f6ae59696bdbab4aa6c6461b27964e2/package.json#L89
https://github.com/Financial-Times/next-article/blob/b8dbd6da13dff427af510fdc8b9f56f135caf544/bower.json#L32
https://github.com/Financial-Times/enterprise-tools/blob/6a6d240b9403240962d6ff4a377a71a52d0427ce/bower.json#L23
https://github.com/Financial-Times/g-components/blob/9fba79d1cc616a9c996f30564c1b4afae1b048f0/bower.json#L30
